// AUTO-GENERATED by @bb/provider's build — do not edit directly.
// Source: browser-bridge/packages/provider/src/types.ts

export type RequestContextKind =
  | "selection"
  | "file"
  | "diagnostics"
  | "git-diff"
  | "note";

export type SourceRange = {
  startLine: number;
  startCharacter: number;
  endLine: number;
  endCharacter: number;
};

export interface RequestContext {
  id: string;
  kind: RequestContextKind;

  prompt: string;

  workspace?: {
    name?: string;
    rootUri?: string;
  };

  source?: {
    uri: string;
    relativePath?: string;
    languageId?: string;
    range?: SourceRange;
    content?: string;
  };

  diagnostics?: Array<{
    message: string;
    severity: "error" | "warning" | "information" | "hint";
    source?: string;
    code?: string | number;
    range?: SourceRange;
  }>;

  git?: {
    repositoryRoot?: string;
    baseRef?: string;
    headRef?: string;
    diff: string;
  };

  note?: {
    noteId?: string;
    title?: string;
    body?: string;
    tags?: string[];
    priority?: number;
  };

  metadata?: Record<string, string | number | boolean>;
}

export type CapturedResponseBlock =
  | {
      type: "markdown";
      content: string;
    }
  | {
      type: "code";
      content: string;
      language?: string;
      filename?: string;
    };

export interface ReviewFinding {
  id: string;

  title: string;
  description: string;

  severity?: "critical" | "high" | "medium" | "low" | "info";
  category?: "bug" | "security" | "performance" | "maintainability" | "style";

  suggestedCode?: string;

  target?: {
    uri?: string;
    range?: SourceRange;
  };

  confidence?: number;
}

export interface CapturedResponse {
  id: string;
  requestId?: string;
  provider: string;

  conversation?: {
    id?: string;
    title?: string;
    url?: string;
  };

  capturedAt: string;

  rawText: string;

  blocks: CapturedResponseBlock[];

  findings?: ReviewFinding[];

  metadata?: {
    model?: string;
    truncated?: boolean;
    responseElementId?: string;
  };
}

export interface BrowserBridgeProvider {
  sendContext(context: RequestContext): Promise<void>;
  captureResponse(): Promise<CapturedResponse>;
  /** Rebinds the bridge server, recovering a wedged connection without a VS Code reload. */
  restartServer(): Promise<void>;
}
